# This is a basic workflow to help you get started with Actions

name: Hello World Workfl
# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  say-hello:
    # The type of runner that the job will run on
    runs-on: self-hosted-runner

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: echo "Hello, world!"
