name: Simple Scheduled Workflow

on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: self-hosted  # This tells the workflow to use your self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Optional step to ensure the repo is checked out

      - name: Say Hello
        run: echo "Hello World - Manual Trigger"