name: Hello World Workflow

on: 
  push:
    branches:
      - main  # This will trigger the workflow when pushing to the 'main' branch

jobs:
  say-hello:
    runs-on: self-hosted  # This tells the workflow to use your self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Optional step to ensure the repo is checked out

      - name: Say Hello
        run: echo "Hello World"
